stages:
  - build
  - trigger

build_image:
  stage: build
  image:
    name: git.loc.gov:4567/fetch/build/kaniko-project/executor:1.0.0
    entrypoint: [""]
  variables:
    IMAGE_FULL_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - echo IMAGE_FULL_TAG $IMAGE_FULL_TAG
    - cp -v images/web.dev.Containerfile Dockerfile
    - echo "VITE_ENV='$DEVELOP_VITE_ENV'" >> env/.env
    - echo "VITE_INV_SERVCE_API='$DEVELOP_VITE_INV_SERVCE_API'" >> env/.env
    - echo "VITE_API_BASE_URI='$DEVELOP_VITE_API_BASE_URI'" >> env/.env
    - cat -A env/.env
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg DEVELOP_VITE_ENV=$DEVELOP_VITE_ENV
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_FULL_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'

build_mr:
  stage: build
  image:
    name: git.loc.gov:4567/fetch/build/kaniko-project/executor:1.0.0
    entrypoint: [""]
  variables:
    IMAGE_FULL_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo IMAGE_FULL_TAG $IMAGE_FULL_TAG
    - cp -v images/web.dev.Containerfile Dockerfile
    - echo "VITE_ENV='$DEVELOP_VITE_ENV'" >> env/.env
    - echo "VITE_INV_SERVCE_API='$DEVELOP_VITE_INV_SERVCE_API'" >> env/.env
    - echo "VITE_API_BASE_URI='$DEVELOP_VITE_API_BASE_URI'" >> env/.env
    - cat -A env/.env
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg VITE_ENV=$DEVELOP_VITE_ENV
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_FULL_TAG
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

trigger_job:
  stage: trigger
  trigger:
    project: fetch/build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_TAG

build_image_test:
  stage: build
  image:
    name: git.loc.gov:4567/fetch/build/kaniko-project/executor:1.0.0
    entrypoint: [""]
  variables:
    IMAGE_FULL_TAG: $CI_REGISTRY_IMAGE/test:latest
  script:
    - echo IMAGE_FULL_TAG $IMAGE_FULL_TAG
    - cp -v images/web.test.Containerfile Dockerfile
    - echo "VITE_ENV='$TEST_VITE_ENV'" >> env/.env
    - echo "VITE_INV_SERVCE_API='$TEST_VITE_INV_SERVCE_API'" >> env/.env
    - echo "VITE_API_BASE_URI='$TEST_VITE_API_BASE_URI'" >> env/.env
    - cat -A env/.env
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg VITE_ENV=$TEST_VITE_ENV
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_FULL_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'

build_image_staging:
  stage: build
  image:
    name: git.loc.gov:4567/fetch/build/kaniko-project/executor:1.0.0
    entrypoint: [""]
  variables:
    IMAGE_FULL_TAG: $CI_REGISTRY_IMAGE/stage:latest
  script:
    - echo IMAGE_FULL_TAG $IMAGE_FULL_TAG
    - cp -v images/web.stage.Containerfile Dockerfile
    - echo "VITE_ENV='$STAGING_VITE_ENV'" >> env/.env
    - echo "VITE_INV_SERVCE_API='$STAGING_VITE_INV_SERVCE_API'" >> env/.env
    - echo "VITE_API_BASE_URI='$STAGING_VITE_API_BASE_URI'" >> env/.env
    - cat -A env/.env
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg VITE_ENV=$STAGING_VITE_ENV
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_FULL_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'staging'
