stages:
  - build
  - trigger

build_image:
  stage: build
  image:
    name: git.loc.gov:4567/fetch/build/kaniko-project/executor:1.0.0
    entrypoint: [""]
  variables:
    IMAGE_FULL_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - echo IMAGE_FULL_TAG $IMAGE_FULL_TAG
    - cp -v images/web.dev.Containerfile Dockerfile
    - echo $DEVELOP_ENV > .env
    - cat .env
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg DEVELOP_VITE_ENV=$DEVELOP_VITE_ENV
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_FULL_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'

build_mr:
  stage: build
  image:
    name: git.loc.gov:4567/fetch/build/kaniko-project/executor:1.0.0
    entrypoint: [""]
  variables:
    IMAGE_FULL_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo IMAGE_FULL_TAG $IMAGE_FULL_TAG
    - echo CI_COMMIT_BRANCH $CI_COMMIT_BRANCH
    - cp -v images/web.dev.Containerfile Dockerfile
    - echo $DEVELOP_ENV > .env
    - cat .env
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg VITE_ENV=$DEVELOP_VITE_ENV
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_FULL_TAG
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

trigger_job:
  stage: trigger
  trigger:
    project: fetch/build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_TAG
  when: manual
