repos:
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.52.0'
    hooks:
    -   id: eslint
        types: [file]
        types_or: [javascript, jsx, vue]
        additional_dependencies:
        -   eslint@8.10.0
        -   eslint-plugin-vue@v9.0.0