export default {
  // example structure for handling api endpoints based on business entities
  // please keep these in alphabetical order and group them if they extend off the same initial url
  // examples: '/examples',
  // examplesNumbers: '/examples/numbers',
  //
  // can be called with the api filter like so
  // this.$api.get(inventoryService.examples, { id: entryId })
  accessionJobs: '/accession-jobs/',
  aisles: '/aisles/',
  authLegacyLogin: '/auth/legacy/login',
  authSsoLogin: '/auth/sso/login/',
  authSsoLogout: '/auth/sso/logout/',
  barcodes: '/barcodes/',
  barcodesValue: '/barcodes/value/',
  buildings: '/buildings/',
  containerTypes: '/container-types/',
  groups: '/groups/',
  items: '/items/',
  mediaTypes: '/media-types/',
  modules: '/modules/',
  nonTrayItems: '/non_tray_items/',
  nonTrayItemsBarcode: '/non_tray_items/barcode/',
  ladders: '/ladders/',
  owners: '/owners/',
  ownersTiers: '/owners/tiers/',
  permissions: '/permissions/',
  picklists: '/pick-lists/',
  refileJobs: '/refile-jobs/',
  refileQueue: '/refile-queue/',
  requests: '/requests/',
  requestsLocations: '/requests/locations',
  requestsPriorities: '/requests/priorities',
  requestsTypes: '/requests/types',
  shelves: '/shelves/',
  shelvesBarcode: '/shelves/barcode/',
  shelvesPositions: '/shelves/positions/',
  shelvingJobs: '/shelving-jobs/',
  sides: '/sides/',
  sizeClass: '/size_class/',
  trays: '/trays/',
  traysBarcode: '/trays/barcode/',
  users: '/users/',
  verificationJobs: '/verification-jobs/'
}